/*
 * TaxCloud.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using TaxCloud.PCL.Controllers;
using TaxCloud.PCL.Http.Client;

namespace TaxCloud.PCL
{
    public partial class TaxCloudClient
    {

        /// <summary>
        /// Singleton access to USMain controller
        /// </summary>
        public USMainController USMain
        {
            get
            {
                return USMainController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public TaxCloudClient() { }
    }
}