/*
 * TaxCloud.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TaxCloud.PCL;
using TaxCloud.PCL.Utilities;

namespace TaxCloud.PCL.Models
{
    public class Address : BaseAuth 
    {
        // These fields hold the values for the public properties.
        private string zip4;
        private string zip5;
        private string state;
        private string city;
        private string address2;
        private string address1;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Zip4")]
        public string Zip4 
        { 
            get 
            {
                return this.zip4; 
            } 
            set 
            {
                this.zip4 = value;
                onPropertyChanged("Zip4");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Zip5")]
        public string Zip5 
        { 
            get 
            {
                return this.zip5; 
            } 
            set 
            {
                this.zip5 = value;
                onPropertyChanged("Zip5");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("State")]
        public string State 
        { 
            get 
            {
                return this.state; 
            } 
            set 
            {
                this.state = value;
                onPropertyChanged("State");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("City")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address2")]
        public string Address2 
        { 
            get 
            {
                return this.address2; 
            } 
            set 
            {
                this.address2 = value;
                onPropertyChanged("Address2");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address1")]
        public string Address1 
        { 
            get 
            {
                return this.address1; 
            } 
            set 
            {
                this.address1 = value;
                onPropertyChanged("Address1");
            }
        }
    }
} 