/*
 * TaxCloud.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TaxCloud.PCL;
using TaxCloud.PCL.Utilities;

namespace TaxCloud.PCL.Models
{
    public class BaseAuth : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string apiLoginID;
        private string apiKey;

        /// <summary>
        /// Your TaxCloud API ID uniquely identifies which Website associated with your TaxCloud account is making this request. Find your API ID(s) in the TaxCloud Websites Area.
        /// </summary>
        [JsonProperty("apiLoginID")]
        public string ApiLoginID 
        { 
            get 
            {
                return this.apiLoginID; 
            } 
            set 
            {
                this.apiLoginID = value;
                onPropertyChanged("ApiLoginID");
            }
        }

        /// <summary>
        /// Your TaxCloud API KEY is a secure generated password issued for each API ID.
        /// </summary>
        [JsonProperty("apiKey")]
        public string ApiKey 
        { 
            get 
            {
                return this.apiKey; 
            } 
            set 
            {
                this.apiKey = value;
                onPropertyChanged("ApiKey");
            }
        }
    }
} 