/*
 * TaxCloud.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using TaxCloud.PCL;
using TaxCloud.PCL.Utilities;

namespace TaxCloud.PCL.Models
{
    public class VerifyAddressResponse : Address 
    {
        // These fields hold the values for the public properties.
        private string errNumber;
        private string errDescription;

        /// <summary>
        /// 0 = Address Verified. IMPORTANT If the address fails to verify (ErrNumber: 9x, ErrDescription "Address can't be verified") that's OK - you should proceed to Lookup using the customer-provided address information.
        /// </summary>
        [JsonProperty("ErrNumber")]
        public string ErrNumber 
        { 
            get 
            {
                return this.errNumber; 
            } 
            set 
            {
                this.errNumber = value;
                onPropertyChanged("ErrNumber");
            }
        }

        /// <summary>
        /// IMPORTANT If the address fails to verify (ErrDescription "Address can't be verified") that's OK - you should proceed to Lookup using the customer-provided address information.
        /// </summary>
        [JsonProperty("ErrDescription")]
        public string ErrDescription 
        { 
            get 
            {
                return this.errDescription; 
            } 
            set 
            {
                this.errDescription = value;
                onPropertyChanged("ErrDescription");
            }
        }
    }
} 